# Generated by Django 5.1.4 on 2024-12-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_paginas", "0002_sucursales_imagen"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipos",
            name="imagen",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="app_paginas/productos/imagenes_productos",
            ),
        ),
        migrations.AddField(
            model_name="kits",
            name="imagen",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="app_paginas/productos/imagenes_productos",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="imagen",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="app_paginas/productos/imagenes_productos",
            ),
        ),
        migrations.AddField(
            model_name="mediocultivo",
            name="imagen",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="app_paginas/productos/imagenes_productos",
            ),
        ),
        migrations.AddField(
            model_name="reactivos",
            name="imagen",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="app_paginas/productos/imagenes_productos",
            ),
        ),
    ]
