# Generated by Django 5.1.4 on 2024-12-23 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_paginas", "0003_equipos_imagen_kits_imagen_material_imagen_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipos",
            name="imagen",
            field=models.ImageField(
                blank=True, null=True, upload_to="app_paginas/imagenes_productos"
            ),
        ),
        migrations.AlterField(
            model_name="kits",
            name="imagen",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/app_paginas/imagenes_productos"
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="imagen",
            field=models.ImageField(
                blank=True, null=True, upload_to="app_paginas/imagenes_productos"
            ),
        ),
        migrations.AlterField(
            model_name="mediocultivo",
            name="imagen",
            field=models.ImageField(
                blank=True, null=True, upload_to="app_paginas/imagenes_productos"
            ),
        ),
        migrations.AlterField(
            model_name="reactivos",
            name="imagen",
            field=models.ImageField(
                blank=True, null=True, upload_to="app_paginas/imagenes_productos"
            ),
        ),
        migrations.AlterField(
            model_name="sucursales",
            name="imagen",
            field=models.ImageField(
                blank=True, null=True, upload_to="app_paginas/imagenes_productos"
            ),
        ),
    ]
