# Generated by Django 5.1.4 on 2024-12-23 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_paginas", "0006_ventaproductos_alter_equipos_imagen_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipos",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="img_equipos"),
        ),
        migrations.AlterField(
            model_name="kits",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="img_kits"),
        ),
        migrations.AlterField(
            model_name="material",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="img_material"),
        ),
        migrations.AlterField(
            model_name="mediocultivo",
            name="imagen",
            field=models.ImageField(
                blank=True, null=True, upload_to="img_medio_cultivo"
            ),
        ),
        migrations.AlterField(
            model_name="reactivos",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="img_reactivos"),
        ),
        migrations.AlterField(
            model_name="sucursales",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="img_sucursales"),
        ),
        migrations.AlterField(
            model_name="ventaproductos",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="img_productos"),
        ),
    ]
