# Generated by Django 5.1.4 on 2024-12-23 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_paginas", "0007_alter_equipos_imagen_alter_kits_imagen_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VentaProductos",
        ),
    ]
