# Generated by Django 5.1.4 on 2024-12-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_paginas", "0008_delete_ventaproductos"),
    ]

    operations = [
        migrations.CreateModel(
            name="VentaProductos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=20)),
                ("descripcion", models.TextField(max_length=200)),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="img_productos"),
                ),
            ],
        ),
    ]
