# Generated by Django 5.1.4 on 2024-12-24 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_paginas", "0010_alter_equipos_descripcion_alter_equipos_nombre_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Equipos",
        ),
        migrations.DeleteModel(
            name="Kits",
        ),
        migrations.DeleteModel(
            name="Material",
        ),
        migrations.DeleteModel(
            name="MedioCultivo",
        ),
        migrations.DeleteModel(
            name="Reactivos",
        ),
    ]
