# Generated by Django 5.1.4 on 2024-12-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_paginas", "0011_delete_equipos_delete_kits_delete_material_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(max_length=1000)),
                ("precio", models.CharField(max_length=15)),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="img_equipos"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Kits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(max_length=1000)),
                ("precio", models.CharField(max_length=15)),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="img_kits"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(max_length=1000)),
                ("precio", models.CharField(max_length=15)),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="img_material"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedioCultivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(max_length=1000)),
                ("precio", models.CharField(max_length=15)),
                (
                    "imagen",
                    models.ImageField(
                        blank=True, null=True, upload_to="img_medio_cultivo"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reactivos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(max_length=1000)),
                ("precio", models.CharField(max_length=15)),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="img_reactivos"),
                ),
            ],
        ),
    ]
