# Generated by Django 5.1.4 on 2024-12-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_paginas", "0013_perfil"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="omag_perfil"),
        ),
    ]
